[mypy]
# Prevent Mypy from crashing if external libraries have missing types.
ignore_missing_imports = True

# Prevent Mypy from forcing strict typing everywhere immediately (increase rigor gradually)
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = False

# Prevent Mypy from complaining if you don't explicitly define the return type (Any)
warn_return_any = False

[mypy-tests.*]
ignore_errors = True
